# Train More - XGB + NN - Achieve LB Boost!
Previously when we ensembled our 7 KFold XGB with our 7 KFold NN, we achieved LB 0.97730 (see [here][1]). 

We will now attempt to boost their CV and LB! Previously our XGB learning rate was 0.1 for experiments. We will now train it with 0.02 for our final submission. Previously our XGB had 7 folds, we will now train it with 10 folds.

Previously our NN had 7 folds, we will now train it with 10 folds. And we will train the same 10 folds 5x times. Each time we will use a different seed.

Afterward, we will ensemble all these new XGB and all these new NN. We will try to beat CV 0.97630 and LB 0.97730 by training more!

==============================

**NOTE** Version 1 and 2 of this notebook have a bug where the OOF and PREDS of the multiple NN are not being saved correctly. Inside each repeat for-loop, the variable OOF and PREDS was being reset to zero. 

[1]: https://www.kaggle.com/code/adilshamim8/bank-term-deposit-prediction
[2]: https://www.kaggle.com/code/cdeotte/xgboost-using-original-data-cv-0-976
[3]: https://www.kaggle.com/code/cdeotte/nn-by-gpt5-cv-0-974-wow

# Load Data
We load train, test, and original datasets. In every Kaggle playground competition, the data is synthetic and it is generated from an original dataset. In this competition, the original dataset is [here][1]

[1]: https://www.kaggle.com/datasets/sushant097/bank-marketing-dataset-full

In [1]:
import pandas as pd, numpy as np, os
import cudf

PATH = "/kaggle/input/playground-series-s5e8/"
train = cudf.read_csv(f"{PATH}train.csv").set_index('id')
print("Train shape", train.shape )
train.head()

Train shape (750000, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
id,,,,,,,,,,,,,,,,,
0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1

In [2]:
test = cudf.read_csv(f"{PATH}test.csv").set_index('id')
test['y'] = np.random.randint(0, 2, len(test))
print("Test shape", test.shape )
test.head()

Test shape (250000, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
id,,,,,,,,,,,,,,,,,
750000,32,blue-collar,married,secondary,no,1397,yes,no,unknown,21,may,224,1,-1,0,unknown,1
750001,44,management,married,tertiary,no,23,yes,no,cellular,3,apr,586,2,-1,0,unknown,1
750002,36,self-employed,married,primary,no,46,yes,yes,cellular,13,may,111,2,-1,0,unknown,1
750003,58,blue-collar,married,secondary,no,-1380,yes,yes,unknown,29,may,125,1,-1,0,unknown,0
750004,28,technician,single,secondary,no,1950,yes,no,cellular,22,jul,181,1,-1,0,unknown,1

In [3]:
orig = cudf.read_csv("/kaggle/input/bank-marketing-dataset-full/bank-full.csv",delimiter=";")
orig['y'] = orig.y.map({'yes':1,'no':0})
orig['id'] = (np.arange(len(orig))+1e6).astype('int')
orig = orig.set_index('id')
print("Original data shape", orig.shape )
orig.head()

Original data shape (45211, 17)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
id,,,,,,,,,,,,,,,,,
1000000,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,0
1000001,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,0
1000002,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,0
1000003,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,0
1000004,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,0

# EDA (Exploratory Data Analysis)
We now combine all data together and then explore the columns and their properties. We observe that there is no missing data. And we observe that the categorical columns have low cardinality (i.e. under 12). We observe that most numerical columns have few unique values, and two numerical columns have around 2k and 8k unique values.

In [4]:
combine = cudf.concat([train,test,orig],axis=0)
print("Combined data shape", combine.shape )

Combined data shape (1045211, 17)

In [5]:
CATS = []
NUMS = []
for c in combine.columns[:-1]:
    t = "CAT"
    if combine[c].dtype=='object':
        CATS.append(c)
    else:
        NUMS.append(c)
        t = "NUM"
    n = combine[c].nunique()
    na = combine[c].isna().sum()
    print(f"[{t}] {c} has {n} unique and {na} NA")
print("CATS:", CATS )
print("NUMS:", NUMS )

[NUM] age has 78 unique and 0 NA
[CAT] job has 12 unique and 0 NA
[CAT] marital has 3 unique and 0 NA
[CAT] education has 4 unique and 0 NA
[CAT] default has 2 unique and 0 NA
[NUM] balance has 8590 unique and 0 NA
[CAT] housing has 2 unique and 0 NA
[CAT] loan has 2 unique and 0 NA
[CAT] contact has 3 unique and 0 NA
[NUM] day has 31 unique and 0 NA
[CAT] month has 12 unique and 0 NA
[NUM] duration has 1824 unique and 0 NA
[NUM] campaign has 52 unique and 0 NA
[NUM] pdays has 628 unique and 0 NA
[NUM] previous has 54 unique and 0 NA
[CAT] poutcome has 4 unique and 0 NA
CATS: ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
NUMS: ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

# Feature Engineer (LE - Label Encode)
We will label encode all categorical columns. Also we will make a duplicate of each numerical column and treat the copy as a categorical column.

In [6]:
CATS1 = []
SIZES = {}
for c in NUMS + CATS:
    n = c
    if c in NUMS: 
        n = f"{c}2"
        CATS1.append(n)
    combine[n],_ = combine[c].factorize()
    SIZES[n] = combine[n].max()+1

    combine[c] = combine[c].astype('int32')
    combine[n] = combine[n].astype('int32')

print("New CATS:", CATS1 )
print("Cardinality of all CATS:", SIZES )

New CATS: ['age2', 'balance2', 'day2', 'duration2', 'campaign2', 'pdays2', 'previous2']
Cardinality of all CATS: {'age2': 78, 'balance2': 8590, 'day2': 31, 'duration2': 1824, 'campaign2': 52, 'pdays2': 628, 'previous2': 54, 'job': 12, 'marital': 3, 'education': 4, 'default': 2, 'housing': 2, 'loan': 2, 'contact': 3, 'month': 12, 'poutcome': 4}

# Feature Engineer (Combine Column Pairs)
We will create a new categorical column from every pair of existing categorical columns. The original categorical columns have been label encoded into integers from `0 to N-1` each. Therefore we can create a new column with unique integers using the formula `new_cols[name] = combine[c1] * SIZES[c2] + combine[c2]`.

In [7]:
from itertools import combinations

pairs = combinations(CATS + CATS1, 2)
new_cols = {}
CATS2 = []

for c1, c2 in pairs:
    name = "_".join(sorted((c1, c2)))
    new_cols[name] = combine[c1] * SIZES[c2] + combine[c2]
    CATS2.append(name)
if new_cols:
    new_df = cudf.DataFrame(new_cols)         
    combine = cudf.concat([combine, new_df], axis=1) 

print(f"Created {len(CATS2)} new CAT columns")

Created 120 new CAT columns

# Feature Engineer (CE - Count Encoding)
We now have 136 categorical columns. We will count encode each of them and create 136 new columns.

In [8]:
CE = []
CC = CATS+CATS1+CATS2
combine['i'] = np.arange( len(combine) )

print(f"Processing {len(CC)} columns... ",end="")
for i,c in enumerate(CC):
    if i%10==0: print(f"{i}, ",end="")
    tmp = combine.groupby(c).y.count()
    tmp = tmp.astype('int32')
    tmp.name = f"CE_{c}"
    CE.append( f"CE_{c}" )
    combine = combine.merge(tmp, on=c, how='left')
combine = combine.sort_values('i')
print()

Processing 136 columns... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130,

In [9]:
train = combine.iloc[:len(train)]
test = combine.iloc[len(train):len(train)+len(test)]
orig = combine.iloc[-len(orig):]
del combine
print("Train shape", train.shape,"Test shape", test.shape,"Original shape", orig.shape )

Train shape (750000, 281) Test shape (250000, 281) Original shape (45211, 281)

# Feature Engineering (TE - Original Data as Cols)
Below is a technique to add the original data as new columns.

In [10]:
TE = []
CC = CATS+CATS1+CATS2

#mn = orig.y.mean() # WE FILL NAN AFTER XGB
print(f"Processing {len(CC)} columns... ",end="")
for i,c in enumerate(CC):
    if i%10==0: print(f"{i}, ",end="")
    tmp = orig.groupby(c).y.mean()
    tmp = tmp.astype('float32')
    NAME = f"TE_ORIG_{c}"
    tmp.name = NAME
    TE.append( NAME )
    train = train.merge(tmp, on=c, how='left')
    #train[NAME] = train[NAME].fillna(mn) # WE FILL NAN AFTER XGB
    test = test.merge(tmp, on=c, how='left')
    #test[NAME] = test[NAME].fillna(mn) # WE FILL NAN AFTER XGB
train = train.sort_values('i')
test = test.sort_values('i')
print()

Processing 136 columns... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130,

# Train More - Train XGB w/ Original Data as Rows
Previously our XGB learning rate was 0.1 for experiments. We will now train it with 0.02 for our final submission. Previously our XGB had 7 folds, we will now train it with 10 folds.

In [11]:
from cuml.preprocessing import TargetEncoder
from sklearn.model_selection import KFold
import xgboost as xgb

print(f"XGBoost version {xgb.__version__}")

FEATURES = NUMS+CATS+CATS1+CATS2+CE
print(f"We have {len(FEATURES)} features.")

FOLDS = 10
SEED = 42

params = {
    "objective": "binary:logistic",  
    "eval_metric": "auc",           
    "learning_rate": 0.02,
    "max_depth": 0,
    "subsample": 0.8,
    "colsample_bytree": 0.7,
    "seed": SEED,
    "device": "cuda",
    "grow_policy": "lossguide", 
    "max_leaves": 32,          
    "alpha": 2.0,
}

class IterLoadForDMatrix(xgb.core.DataIter):
    def __init__(self, df=None, features=None, target=None, batch_size=256*1024):
        self.features = features
        self.target = target
        self.df = df
        self.it = 0 
        self.batch_size = batch_size
        self.batches = int( np.ceil( len(df) / self.batch_size ) )
        super().__init__()

    def reset(self):
        '''Reset the iterator'''
        self.it = 0

    def next(self, input_data):
        '''Yield next batch of data.'''
        if self.it == self.batches:
            return 0 # Return 0 when there's no more batch.
        
        a = self.it * self.batch_size
        b = min( (self.it + 1) * self.batch_size, len(self.df) )
        #dt = cudf.DataFrame(self.df.iloc[a:b])
        dt = self.df.iloc[a:b]
        input_data(data=dt[self.features], label=dt[self.target]) 
        self.it += 1
        return 1

oof_preds = np.zeros(len(train))
test_preds = np.zeros(len(test))

REPEATS = 1
for kk in range(REPEATS):
    kf = KFold(n_splits=FOLDS, shuffle=True, random_state=SEED)
    for fold, (train_idx, val_idx) in enumerate(kf.split(train)):
        print("#"*25)
        print(f"### REPEAT {kk+1}, Fold {fold+1} ###")
        print("#"*25)
    
        Xy_train = train.iloc[train_idx][ FEATURES+['y'] ].copy()
        Xy_more = orig[ FEATURES+['y'] ]
        for k in range(1):
            Xy_train = cudf.concat([Xy_train,Xy_more],axis=0,ignore_index=True)
        
        X_valid = train.iloc[val_idx][FEATURES].copy()
        y_valid = train.iloc[val_idx]['y']
        X_test = test[FEATURES].copy()
    
        CC = CATS1+CATS2
        print(f"Target encoding {len(CC)} features... ",end="")
        for i,c in enumerate(CC):
            if i%10==0: print(f"{i}, ",end="")
            TE0 = TargetEncoder(n_folds=10, smooth=0, split_method='random', stat='mean')
            Xy_train[c] = TE0.fit_transform(Xy_train[c],Xy_train['y']).astype('float32')
            X_valid[c] = TE0.transform(X_valid[c]).astype('float32')
            X_test[c] = TE0.transform(X_test[c]).astype('float32')
        print()
    
        Xy_train[CATS] = Xy_train[CATS].astype('category')
        X_valid[CATS] = X_valid[CATS].astype('category')
        X_test[CATS] = X_test[CATS].astype('category')
    
        Xy_train = IterLoadForDMatrix(Xy_train, FEATURES, 'y')
        dtrain = xgb.QuantileDMatrix(Xy_train, enable_categorical=True, max_bin=256)
        dval   = xgb.DMatrix(X_valid, label=y_valid, enable_categorical=True)
        dtest  = xgb.DMatrix(X_test, enable_categorical=True)
    
        params['seed'] = kk*FOLDS + fold
        model = xgb.train(
            params=params,
            dtrain=dtrain,
            num_boost_round=100_000, 
            evals=[(dtrain, "train"), (dval, "valid")],
            early_stopping_rounds=250,
            verbose_eval=500
        )
    
        oof_preds[val_idx] += model.predict(dval, iteration_range=(0, model.best_iteration + 1)) / REPEATS
        test_preds += model.predict(dtest, iteration_range=(0, model.best_iteration + 1)) / FOLDS / REPEATS

XGBoost version 2.0.3
We have 279 features.
#########################
### REPEAT 1, Fold 1 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94638	valid-auc:0.94769
[500]	train-auc:0.97518	valid-auc:0.97460
[1000]	train-auc:0.97757	valid-auc:0.97530
[1500]	train-auc:0.97935	valid-auc:0.97550
[2000]	train-auc:0.98092	valid-auc:0.97566
[2500]	train-auc:0.98234	valid-auc:0.97574
[3000]	train-auc:0.98366	valid-auc:0.97580
[3500]	train-auc:0.98486	valid-auc:0.97585
[4000]	train-auc:0.98598	valid-auc:0.97586
[4500]	train-auc:0.98705	valid-auc:0.97588
[5000]	train-auc:0.98803	valid-auc:0.97588
[5002]	train-auc:0.98803	valid-auc:0.97588
#########################
### REPEAT 1, Fold 2 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94960	valid-auc:0.95271
[500]	train-auc:0.97518	valid-auc:0.97487
[1000]	train-auc:0.97758	valid-auc:0.97549
[1500]	train-auc:0.97938	valid-auc:0.97571
[2000]	train-auc:0.98093	valid-auc:0.97579
[2500]	train-auc:0.98236	valid-auc:0.97586
[3000]	train-auc:0.98367	valid-auc:0.97591
[3500]	train-auc:0.98489	valid-auc:0.97593
[3914]	train-auc:0.98582	valid-auc:0.97594
#########################
### REPEAT 1, Fold 3 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94853	valid-auc:0.95158
[500]	train-auc:0.97519	valid-auc:0.97477
[1000]	train-auc:0.97759	valid-auc:0.97545
[1500]	train-auc:0.97939	valid-auc:0.97571
[2000]	train-auc:0.98097	valid-auc:0.97583
[2500]	train-auc:0.98237	valid-auc:0.97592
[3000]	train-auc:0.98370	valid-auc:0.97598
[3500]	train-auc:0.98491	valid-auc:0.97606
[4000]	train-auc:0.98605	valid-auc:0.97610
[4500]	train-auc:0.98710	valid-auc:0.97612
[5000]	train-auc:0.98806	valid-auc:0.97615
[5500]	train-auc:0.98898	valid-auc:0.97617
[5911]	train-auc:0.98968	valid-auc:0.97617
#########################
### REPEAT 1, Fold 4 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95505	valid-auc:0.95548
[500]	train-auc:0.97525	valid-auc:0.97391
[1000]	train-auc:0.97764	valid-auc:0.97460
[1500]	train-auc:0.97944	valid-auc:0.97487
[2000]	train-auc:0.98099	valid-auc:0.97501
[2500]	train-auc:0.98242	valid-auc:0.97510
[3000]	train-auc:0.98373	valid-auc:0.97517
[3500]	train-auc:0.98493	valid-auc:0.97520
[4000]	train-auc:0.98605	valid-auc:0.97521
[4500]	train-auc:0.98708	valid-auc:0.97523
[5000]	train-auc:0.98806	valid-auc:0.97524
[5500]	train-auc:0.98896	valid-auc:0.97524
[5690]	train-auc:0.98929	valid-auc:0.97523
#########################
### REPEAT 1, Fold 5 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94739	valid-auc:0.95125
[500]	train-auc:0.97521	valid-auc:0.97436
[1000]	train-auc:0.97761	valid-auc:0.97501
[1500]	train-auc:0.97940	valid-auc:0.97521
[2000]	train-auc:0.98097	valid-auc:0.97532
[2500]	train-auc:0.98239	valid-auc:0.97540
[3000]	train-auc:0.98369	valid-auc:0.97545
[3500]	train-auc:0.98489	valid-auc:0.97548
[4000]	train-auc:0.98603	valid-auc:0.97551
[4500]	train-auc:0.98706	valid-auc:0.97553
[4729]	train-auc:0.98751	valid-auc:0.97552
#########################
### REPEAT 1, Fold 6 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94557	valid-auc:0.94843
[500]	train-auc:0.97521	valid-auc:0.97484
[1000]	train-auc:0.97760	valid-auc:0.97544
[1500]	train-auc:0.97939	valid-auc:0.97566
[2000]	train-auc:0.98095	valid-auc:0.97579
[2500]	train-auc:0.98239	valid-auc:0.97587
[3000]	train-auc:0.98371	valid-auc:0.97592
[3500]	train-auc:0.98490	valid-auc:0.97596
[4000]	train-auc:0.98602	valid-auc:0.97601
[4314]	train-auc:0.98668	valid-auc:0.97600
#########################
### REPEAT 1, Fold 7 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94524	valid-auc:0.95056
[500]	train-auc:0.97513	valid-auc:0.97587
[1000]	train-auc:0.97751	valid-auc:0.97637
[1500]	train-auc:0.97932	valid-auc:0.97657
[2000]	train-auc:0.98091	valid-auc:0.97669
[2500]	train-auc:0.98233	valid-auc:0.97675
[3000]	train-auc:0.98365	valid-auc:0.97680
[3500]	train-auc:0.98487	valid-auc:0.97684
[4000]	train-auc:0.98599	valid-auc:0.97685
[4074]	train-auc:0.98615	valid-auc:0.97685
#########################
### REPEAT 1, Fold 8 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94753	valid-auc:0.94958
[500]	train-auc:0.97516	valid-auc:0.97490
[1000]	train-auc:0.97758	valid-auc:0.97557
[1500]	train-auc:0.97938	valid-auc:0.97576
[2000]	train-auc:0.98093	valid-auc:0.97584
[2500]	train-auc:0.98234	valid-auc:0.97591
[3000]	train-auc:0.98363	valid-auc:0.97595
[3500]	train-auc:0.98484	valid-auc:0.97600
[4000]	train-auc:0.98597	valid-auc:0.97603
[4500]	train-auc:0.98702	valid-auc:0.97604
[5000]	train-auc:0.98799	valid-auc:0.97605
[5132]	train-auc:0.98824	valid-auc:0.97605
#########################
### REPEAT 1, Fold 9 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95293	valid-auc:0.95521
[500]	train-auc:0.97511	valid-auc:0.97502
[1000]	train-auc:0.97753	valid-auc:0.97566
[1500]	train-auc:0.97933	valid-auc:0.97586
[2000]	train-auc:0.98091	valid-auc:0.97596
[2500]	train-auc:0.98232	valid-auc:0.97601
[3000]	train-auc:0.98365	valid-auc:0.97603
[3396]	train-auc:0.98463	valid-auc:0.97603
#########################
### REPEAT 1, Fold 10 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94853	valid-auc:0.95354
[500]	train-auc:0.97507	valid-auc:0.97619
[1000]	train-auc:0.97749	valid-auc:0.97678
[1500]	train-auc:0.97929	valid-auc:0.97696
[2000]	train-auc:0.98087	valid-auc:0.97707
[2500]	train-auc:0.98231	valid-auc:0.97713
[3000]	train-auc:0.98362	valid-auc:0.97717
[3500]	train-auc:0.98485	valid-auc:0.97721
[4000]	train-auc:0.98597	valid-auc:0.97723
[4100]	train-auc:0.98619	valid-auc:0.97723

In [12]:
from sklearn.metrics import roc_auc_score

m = roc_auc_score(train.y.to_numpy(), oof_preds)
print(f"XGB (Train More) with Original Data as rows CV = {m}")

XGB (Train More) with Original Data as rows CV = 0.9760909064923055

# Train More - Train XGB w/ Original Data as Cols
Previously our XGB learning rate was 0.1 for experiments. We will now train it with 0.02 for our final submission. Previously our XGB had 7 folds, we will now train it with 10 folds.

In [13]:
FEATURES += TE
print(f"We have {len(FEATURES)} features.")

oof_preds2 = np.zeros(len(train))
test_preds2 = np.zeros(len(test))

REPEATS = 1
for kk in range(REPEATS):
    kf = KFold(n_splits=FOLDS, shuffle=True, random_state=SEED)
    for fold, (train_idx, val_idx) in enumerate(kf.split(train)):
        print("#"*25)
        print(f"### REPEAT {kk+1}, Fold {fold+1} ###")
        print("#"*25)
    
        Xy_train = train.iloc[train_idx][ FEATURES+['y'] ].copy()  
        X_valid = train.iloc[val_idx][FEATURES].copy()
        y_valid = train.iloc[val_idx]['y']
        X_test = test[FEATURES].copy()
    
        CC = CATS1+CATS2
        print(f"Target encoding {len(CC)} features... ",end="")
        for i,c in enumerate(CC):
            if i%10==0: print(f"{i}, ",end="")
            TE0 = TargetEncoder(n_folds=10, smooth=0, split_method='random', stat='mean')
            Xy_train[c] = TE0.fit_transform(Xy_train[c],Xy_train['y']).astype('float32')
            X_valid[c] = TE0.transform(X_valid[c]).astype('float32')
            X_test[c] = TE0.transform(X_test[c]).astype('float32')
        print()
    
        Xy_train[CATS] = Xy_train[CATS].astype('category')
        X_valid[CATS] = X_valid[CATS].astype('category')
        X_test[CATS] = X_test[CATS].astype('category')
    
        Xy_train = IterLoadForDMatrix(Xy_train, FEATURES, 'y')
        dtrain = xgb.QuantileDMatrix(Xy_train, enable_categorical=True, max_bin=256)
        dval   = xgb.DMatrix(X_valid, label=y_valid, enable_categorical=True)
        dtest  = xgb.DMatrix(X_test, enable_categorical=True)
    
        params['seed'] = kk*FOLDS + fold 
        model = xgb.train(
            params=params,
            dtrain=dtrain,
            num_boost_round=100_000, 
            evals=[(dtrain, "train"), (dval, "valid")],
            early_stopping_rounds=250,
            verbose_eval=500
        )
    
        oof_preds2[val_idx] += model.predict(dval, iteration_range=(0, model.best_iteration + 1)) / REPEATS
        test_preds2 += model.predict(dtest, iteration_range=(0, model.best_iteration + 1)) / FOLDS / REPEATS

# FILL NAN FOR NN BELOW (we skipped this above for xgb)
CC = CATS+CATS1+CATS2
mn = orig.y.mean()
for i,c in enumerate(CC):
    NAME = f"TE_ORIG_{c}"
    train[NAME] = train[NAME].fillna(mn)
    test[NAME] = test[NAME].fillna(mn)

We have 415 features.
#########################
### REPEAT 1, Fold 1 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95059	valid-auc:0.94970
[500]	train-auc:0.97694	valid-auc:0.97475
[1000]	train-auc:0.97948	valid-auc:0.97547
[1500]	train-auc:0.98133	valid-auc:0.97573
[2000]	train-auc:0.98296	valid-auc:0.97586
[2500]	train-auc:0.98444	valid-auc:0.97595
[3000]	train-auc:0.98581	valid-auc:0.97600
[3400]	train-auc:0.98680	valid-auc:0.97601
#########################
### REPEAT 1, Fold 2 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95047	valid-auc:0.94998
[500]	train-auc:0.97695	valid-auc:0.97490
[1000]	train-auc:0.97947	valid-auc:0.97560
[1500]	train-auc:0.98134	valid-auc:0.97582
[2000]	train-auc:0.98296	valid-auc:0.97591
[2500]	train-auc:0.98443	valid-auc:0.97599
[3000]	train-auc:0.98578	valid-auc:0.97602
[3500]	train-auc:0.98703	valid-auc:0.97607
[4000]	train-auc:0.98817	valid-auc:0.97608
[4043]	train-auc:0.98826	valid-auc:0.97609
#########################
### REPEAT 1, Fold 3 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95053	valid-auc:0.94990
[500]	train-auc:0.97695	valid-auc:0.97487
[1000]	train-auc:0.97946	valid-auc:0.97564
[1500]	train-auc:0.98132	valid-auc:0.97582
[2000]	train-auc:0.98295	valid-auc:0.97592
[2500]	train-auc:0.98442	valid-auc:0.97600
[3000]	train-auc:0.98578	valid-auc:0.97607
[3500]	train-auc:0.98701	valid-auc:0.97611
[4000]	train-auc:0.98815	valid-auc:0.97613
[4500]	train-auc:0.98922	valid-auc:0.97612
[4501]	train-auc:0.98922	valid-auc:0.97612
#########################
### REPEAT 1, Fold 4 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95397	valid-auc:0.95111
[500]	train-auc:0.97703	valid-auc:0.97387
[1000]	train-auc:0.97950	valid-auc:0.97462
[1500]	train-auc:0.98137	valid-auc:0.97484
[2000]	train-auc:0.98301	valid-auc:0.97495
[2500]	train-auc:0.98447	valid-auc:0.97504
[3000]	train-auc:0.98581	valid-auc:0.97510
[3500]	train-auc:0.98705	valid-auc:0.97513
[4000]	train-auc:0.98820	valid-auc:0.97517
[4291]	train-auc:0.98881	valid-auc:0.97517
#########################
### REPEAT 1, Fold 5 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.94948	valid-auc:0.95094
[500]	train-auc:0.97699	valid-auc:0.97452
[1000]	train-auc:0.97949	valid-auc:0.97524
[1500]	train-auc:0.98133	valid-auc:0.97547
[2000]	train-auc:0.98295	valid-auc:0.97561
[2500]	train-auc:0.98442	valid-auc:0.97568
[3000]	train-auc:0.98577	valid-auc:0.97574
[3500]	train-auc:0.98701	valid-auc:0.97577
[3807]	train-auc:0.98773	valid-auc:0.97576
#########################
### REPEAT 1, Fold 6 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95145	valid-auc:0.95095
[500]	train-auc:0.97694	valid-auc:0.97489
[1000]	train-auc:0.97946	valid-auc:0.97569
[1500]	train-auc:0.98132	valid-auc:0.97592
[2000]	train-auc:0.98294	valid-auc:0.97605
[2500]	train-auc:0.98442	valid-auc:0.97613
[3000]	train-auc:0.98576	valid-auc:0.97620
[3500]	train-auc:0.98700	valid-auc:0.97624
[4000]	train-auc:0.98813	valid-auc:0.97626
[4500]	train-auc:0.98919	valid-auc:0.97628
[4971]	train-auc:0.99010	valid-auc:0.97629
#########################
### REPEAT 1, Fold 7 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95435	valid-auc:0.95627
[500]	train-auc:0.97691	valid-auc:0.97601
[1000]	train-auc:0.97941	valid-auc:0.97658
[1500]	train-auc:0.98127	valid-auc:0.97676
[2000]	train-auc:0.98291	valid-auc:0.97684
[2500]	train-auc:0.98437	valid-auc:0.97688
[3000]	train-auc:0.98573	valid-auc:0.97691
[3500]	train-auc:0.98698	valid-auc:0.97693
[3855]	train-auc:0.98781	valid-auc:0.97693
#########################
### REPEAT 1, Fold 8 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95042	valid-auc:0.95012
[500]	train-auc:0.97694	valid-auc:0.97509
[1000]	train-auc:0.97942	valid-auc:0.97582
[1500]	train-auc:0.98126	valid-auc:0.97602
[2000]	train-auc:0.98289	valid-auc:0.97617
[2500]	train-auc:0.98435	valid-auc:0.97624
[3000]	train-auc:0.98571	valid-auc:0.97628
[3500]	train-auc:0.98695	valid-auc:0.97632
[4000]	train-auc:0.98809	valid-auc:0.97634
[4432]	train-auc:0.98900	valid-auc:0.97634
#########################
### REPEAT 1, Fold 9 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95297	valid-auc:0.95256
[500]	train-auc:0.97690	valid-auc:0.97509
[1000]	train-auc:0.97940	valid-auc:0.97583
[1500]	train-auc:0.98128	valid-auc:0.97605
[2000]	train-auc:0.98292	valid-auc:0.97617
[2500]	train-auc:0.98438	valid-auc:0.97626
[3000]	train-auc:0.98574	valid-auc:0.97631
[3500]	train-auc:0.98698	valid-auc:0.97633
[3514]	train-auc:0.98701	valid-auc:0.97633
#########################
### REPEAT 1, Fold 10 ###
#########################
Target encoding 127 features... 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,

/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:839: FutureWarning: Index.format is deprecated and will be removed in a future version. Convert using index.astype(str) or index.map(formatter) instead.
  feature_names = data.columns.format()

[0]	train-auc:0.95448	valid-auc:0.95601
[500]	train-auc:0.97681	valid-auc:0.97647
[1000]	train-auc:0.97932	valid-auc:0.97712
[1500]	train-auc:0.98120	valid-auc:0.97731
[2000]	train-auc:0.98286	valid-auc:0.97743
[2500]	train-auc:0.98433	valid-auc:0.97750
[3000]	train-auc:0.98568	valid-auc:0.97754
[3500]	train-auc:0.98694	valid-auc:0.97755
[3762]	train-auc:0.98755	valid-auc:0.97755

In [14]:
from sklearn.metrics import roc_auc_score

m = roc_auc_score(train.y.to_numpy(), oof_preds2)
print(f"XGB (Train More) with Original Data as rows CV = {m}")

XGB (Train More) with Original Data as rows CV = 0.9762627854582778

# Normalize
NN prefer numerical columns to be Gaussian distributed. Therefore we first apply log transform to skewed distributions and then standardize with subtract mean divide standard deviation. (The standardization code is included in the NN code below).

In [15]:
LOG = ['balance','duration','campaign','pdays','previous']

for c in LOG+CE:
    if c in LOG: 
        mn = min( (train[c].min(), test[c].min()) )
        train[c] = train[c]-mn
        test[c] = test[c]-mn
    train[c] = np.log1p( train[c] )
    test[c] = np.log1p( test[c] )

In [16]:
FEATURES = CATS+NUMS+CATS1+CE+TE
TARGET_COL = 'y'
print(f"We have {len( FEATURES )} features.")

We have 295 features.

# Train More - NN by GPT5 - Vibe Coding!
I used my features from my XGBoost starter notebook, and then asked GPT5 to build me a NN MLP. Below is what GPT5 produced! Here is the prompt I asked GPT5:

>I have dataframe with 16 categorical features. And i have 279 numeric features. This is in a Pandas dataframe. Can you write me code that builds and trains a Pytorch MLP that uses embeddings for the categoricals and predicts a binary target? Please make the model, set the training schedule. Write a KFold training loop, save the OOF, etc

After it produced the code, I tuned the batch size, learning rate, and learning schedule. Everything else was created by GPT5! Wow!

Previously our NN had 7 folds, we will now train it with 10 folds. And we will train the same 10 folds 5x times. Each time we will use a different seed. Then we will average all the models.

In [17]:
# =========================
# PyTorch MLP w/ Cat Embeddings + KFold OOF
# =========================
import os, math, random, gc, json
import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import roc_auc_score, log_loss, accuracy_score

# -------------------------
# Config
# -------------------------
SEED          = 42
FOLDS         = 10
EPOCHS        = 4
BATCH_SIZE    = 512
LR_MAX        = 3e-3          # peak LR for OneCycle
WD            = 1e-4          # weight decay (AdamW)
EARLY_STOP    = 4             # epochs with no val AUC improvement
GRAD_CLIP     = 1.0
NUM_WORKERS   = 4
MODEL_DIR     = "./mlp_catemb_models"
OOF_PATH      = "./oof_catemb.csv"

os.makedirs(MODEL_DIR, exist_ok=True)

KNOWN_CARDINALITIES = SIZES
df = train[ FEATURES+['y'] ].to_pandas()
df2 = test[ FEATURES+['y'] ].to_pandas()

# -------------------------
# Repro
# -------------------------
def seed_everything(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(SEED)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# -------------------------
# Load/define your dataframe `df`
# -------------------------
# df = pd.read_parquet("your_data.parquet")
# assert TARGET_COL in df.columns

categorical_cols = list( KNOWN_CARDINALITIES.keys() )
numeric_cols = [c for c in df.columns if c not in categorical_cols + [TARGET_COL]]

print(f"#categoricals={len(categorical_cols)}, #numerics={len(numeric_cols)}")

# -------------------------
# Label-encode categoricals (reserve 0=UNK)
# -------------------------
encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    tmp = pd.concat([ df[[col]],df2[[col]] ],axis=0)
    tmp[col] = tmp[col].astype(str).fillna("NaN")
    le.fit(tmp[col].values)
    df[col] = le.transform(df[col].astype(str).values) + 1
    df2[col] = le.transform(df2[col].astype(str).values) + 1
    encoders[col] = le
    del tmp

cardinalities = {}
for col in categorical_cols:
    if col in KNOWN_CARDINALITIES:
        cardinalities[col] = KNOWN_CARDINALITIES[col] + 1  # +1 for UNK
        df[col] = np.clip(df[col], 0, KNOWN_CARDINALITIES[col])
        df2[col] = np.clip(df2[col], 0, KNOWN_CARDINALITIES[col])
    else:
        cardinalities[col] = int( max(df[col].max(),df2[col].max()) ) + 1

# -------------------------
# Scale numerics
# -------------------------
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols].astype(np.float32))
df2[numeric_cols] = scaler.transform(df2[numeric_cols].astype(np.float32))

# -------------------------
# Embedding dims
# -------------------------
def emb_dim_from_card(n):
    return int(min(50, round(1.6 * (n**0.56))))

emb_info = [(cardinalities[c], emb_dim_from_card(cardinalities[c])) for c in categorical_cols]
total_emb_dim = sum(d for _, d in emb_info)
print("Embedding config:", dict(zip(categorical_cols, emb_info)))
print("Total embedding dim:", total_emb_dim, " + numeric:", len(numeric_cols))

# -------------------------
# Dataset
# -------------------------
class TabDataset(Dataset):
    def __init__(self, df, cat_cols, num_cols, target_col=None, idx=None):
        self.cat_cols = cat_cols
        self.num_cols = num_cols
        self.target_col = target_col
        self.df = df if idx is None else df.iloc[idx]
        self.cats = self.df[self.cat_cols].values.astype(np.int64)
        self.nums = self.df[self.num_cols].values.astype(np.float32)
        self.y = None if self.target_col is None else self.df[self.target_col].values.astype(np.float32)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, i):
        cats = torch.from_numpy(self.cats[i])
        nums = torch.from_numpy(self.nums[i])
        if self.y is None:
            return cats, nums
        return cats, nums, torch.tensor(self.y[i])

# -------------------------
# Model
# -------------------------
class MLPWithCatEmb(nn.Module):
    def __init__(self, emb_info, n_num, hidden=[512, 256, 128], dropout=0.15):
        super().__init__()
        self.emb_layers = nn.ModuleList(
            [nn.Embedding(num_embeddings=card, embedding_dim=dim, padding_idx=0)
             for card, dim in emb_info]
        )
        emb_total = sum(dim for _, dim in emb_info)
        in_dim = emb_total + n_num

        self.bn_nums = nn.BatchNorm1d(n_num) if n_num > 0 else nn.Identity()
        self.dropout = nn.Dropout(dropout)

        layers = []
        last = in_dim
        for h in hidden:
            layers += [
                nn.Linear(last, h),
                nn.BatchNorm1d(h),
                nn.SiLU(),
                nn.Dropout(dropout)
            ]
            last = h
        self.mlp = nn.Sequential(*layers)
        self.head = nn.Linear(last, 1)

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
                if m.bias is not None:
                    nn.init.zeros_(m.bias)

    def forward(self, x_cat, x_num):
        emb = [emb_layer(x_cat[:, i]) for i, emb_layer in enumerate(self.emb_layers)]
        x_emb = torch.cat(emb, dim=1) if emb else None
        if x_num is not None and x_num.shape[1] > 0:
            x_num = self.bn_nums(x_num)
            x = torch.cat([x_emb, x_num], dim=1) if x_emb is not None else x_num
        else:
            x = x_emb
        x = self.mlp(x)
        logit = self.head(x).squeeze(1)
        return logit

# -------------------------
# Train / Eval helpers
# -------------------------
def train_one_epoch(model, loader, optimizer, scaler, scheduler=None):
    model.train()
    running = 0.0
    for cats, nums, y in loader:
        cats = cats.to(device, non_blocking=True)
        nums = nums.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast('cuda', enabled=True):
            logits = model(cats, nums)
            loss = F.binary_cross_entropy_with_logits(logits, y)
        scaler.scale(loss).backward()
        if GRAD_CLIP is not None:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
        scaler.step(optimizer)
        scaler.update()
        if scheduler is not None:
            scheduler.step()

        running += loss.detach().item() * y.size(0)
    return running / len(loader.dataset)

@torch.no_grad()
def validate(model, loader):
    model.eval()
    all_logits, all_y = [], []
    for batch in loader:
        if len(batch) == 3:
            cats, nums, y = batch
            all_y.append(y.detach().cpu())
        else:
            cats, nums = batch
        cats = cats.to(device, non_blocking=True)
        nums = nums.to(device, non_blocking=True)
        all_logits.append(model(cats, nums).detach().cpu())

    logits = torch.cat(all_logits).numpy()
    probs  = 1.0 / (1.0 + np.exp(-logits))
    probs_c = np.clip(probs, 1e-7, 1 - 1e-7)  # clip instead of log_loss(..., eps=...)

    if all_y:
        y_true = torch.cat(all_y).numpy().astype(np.int64)
        auc = roc_auc_score(y_true, probs)
        ll  = log_loss(y_true, probs_c)
        acc = accuracy_score(y_true, (probs >= 0.5).astype(int))
        return probs, {"auc": auc, "logloss": ll, "acc": acc}
    return probs, {}

oof = np.zeros(len(df), dtype=np.float32)
preds = np.zeros(len(df2), dtype=np.float32)

REPEATS = 5
for kk in range(REPEATS):
    print(f"##### REPEAT {kk+1} of {REPEATS} #####")
    seed_everything(SEED+kk)

    # -------------------------
    # KFold training
    # -------------------------
    skf = KFold(n_splits=FOLDS, shuffle=True, random_state=SEED)
    
    y = df[TARGET_COL].astype(int).values
    oof2 = np.zeros(len(df), dtype=np.float32)
    fold_metrics = []
    
    for fold, (trn_idx, val_idx) in enumerate(skf.split(df, y), start=1):
        print(f"\n========== Fold {fold}/{FOLDS} ==========")
        trn_ds = TabDataset(df, categorical_cols, numeric_cols, TARGET_COL, trn_idx)
        val_ds = TabDataset(df, categorical_cols, numeric_cols, TARGET_COL, val_idx)
        test_ds = TabDataset(df2, categorical_cols, numeric_cols, TARGET_COL, np.arange(len(df2)) )
    
        trn_loader = DataLoader(
            trn_ds, batch_size=BATCH_SIZE, shuffle=True,
            num_workers=NUM_WORKERS, pin_memory=True, drop_last=True
        )
        val_loader = DataLoader(
            val_ds, batch_size=BATCH_SIZE, shuffle=False,
            num_workers=NUM_WORKERS, pin_memory=True
        )
        test_loader = DataLoader(
            test_ds, batch_size=BATCH_SIZE, shuffle=False,
            num_workers=NUM_WORKERS, pin_memory=True
        )
    
        model = MLPWithCatEmb(emb_info=emb_info, n_num=len(numeric_cols)).to(device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=LR_MAX, weight_decay=WD)
    
        total_steps = EPOCHS * len(trn_loader)
        scheduler = torch.optim.lr_scheduler.OneCycleLR(
            optimizer, max_lr=LR_MAX, total_steps=total_steps,
            pct_start=0.0, div_factor=25.0, final_div_factor=10.5, anneal_strategy='cos'
        )
    
        scaler = torch.amp.GradScaler('cuda', enabled=True)
    
        best_auc = -1.0
        best_epoch = -1
        epochs_no_improve = 0
        best_path = os.path.join(MODEL_DIR, f"fold{fold}.pt")
    
        for epoch in range(1, EPOCHS+1):
            train_loss = train_one_epoch(model, trn_loader, optimizer, scaler, scheduler)
            _, val_stats = validate(model, val_loader)
            auc = val_stats.get("auc", float("nan"))
            print(f"Epoch {epoch:02d}: train_loss={train_loss:.4f} | "
                  f"val_auc={auc:.5f} val_logloss={val_stats['logloss']:.5f} val_acc={val_stats['acc']:.4f}")
    
            if 1: #auc > best_auc:
                best_auc = auc
                best_epoch = epoch
                epochs_no_improve = 0
                torch.save({
                    "model_state": model.state_dict(),
                    "config": {
                        "emb_info": emb_info,
                        "numeric_cols": numeric_cols,
                        "categorical_cols": categorical_cols
                    }
                }, best_path)
            else:
                epochs_no_improve += 1
                if epochs_no_improve >= EARLY_STOP:
                    print(f"Early stopping at epoch {epoch}. Best AUC {best_auc:.5f} @ epoch {best_epoch}")
                    break
    
        # Load best
        ckpt = torch.load(best_path, map_location="cpu", weights_only=False)
        model.load_state_dict(ckpt["model_state"])
        model.to(device)
    
        # OOF for this fold
        val_probs, val_stats = validate(model, val_loader)
        oof[val_idx] += val_probs / REPEATS
        oof2[val_idx] = val_probs
        fold_metrics.append({"fold": fold, **val_stats})
        print(f"[Fold {fold}] AUC={val_stats['auc']:.5f}  LogLoss={val_stats['logloss']:.5f}  Acc={val_stats['acc']:.4f}")
    
        test_probs, _ = validate(model, test_loader)
        preds += test_probs / FOLDS / REPEATS
    
    # -------------------------
    # Overall OOF metrics
    # -------------------------
    oof_c = np.clip(oof2, 1e-7, 1 - 1e-7)
    oof_auc = roc_auc_score(y, oof2)
    oof_ll  = log_loss(y, oof_c)     # no eps kwarg
    oof_acc = accuracy_score(y, (oof2>=0.5).astype(int))
    print("\n========== Overall OOF ==========")
    print(f"OOF AUC={oof_auc:.5f}  LogLoss={oof_ll:.5f}  Acc={oof_acc:.4f}")
    
    # Save OOF and metrics
    #pd.DataFrame({
    #    "oof_pred": oof,
    #    TARGET_COL: y
    #}).to_csv(OOF_PATH, index=False)
    
    #with open(os.path.join(MODEL_DIR, "fold_metrics.json"), "w") as f:
    #    json.dump({"folds": fold_metrics, "oof": {"auc": oof_auc, "logloss": oof_ll, "acc": oof_acc}}, f, indent=2)
    
    #print(f"Saved OOF -> {OOF_PATH}")
    #print(f"Saved models -> {MODEL_DIR}")

Device: cuda
#categoricals=16, #numerics=279
Embedding config: {'age2': (79, 18), 'balance2': (8591, 50), 'day2': (32, 11), 'duration2': (1825, 50), 'campaign2': (53, 15), 'pdays2': (629, 50), 'previous2': (55, 15), 'job': (13, 7), 'marital': (4, 3), 'education': (5, 4), 'default': (3, 3), 'housing': (3, 3), 'loan': (3, 3), 'contact': (4, 3), 'month': (13, 7), 'poutcome': (5, 4)}
Total embedding dim: 246  + numeric: 279
##### REPEAT 1 of 5 #####

========== Fold 1/10 ==========
Epoch 01: train_loss=0.1500 | val_auc=0.97228 val_logloss=0.13612 val_acc=0.9414
Epoch 02: train_loss=0.1318 | val_auc=0.97392 val_logloss=0.13125 val_acc=0.9431
Epoch 03: train_loss=0.1246 | val_auc=0.97426 val_logloss=0.13148 val_acc=0.9437
Epoch 04: train_loss=0.1196 | val_auc=0.97416 val_logloss=0.13127 val_acc=0.9434
[Fold 1] AUC=0.97416  LogLoss=0.13127  Acc=0.9434

========== Fold 2/10 ==========
Epoch 01: train_loss=0.1514 | val_auc=0.97207 val_logloss=0.13602 val_acc=0.9418
Epoch 02: train_loss=0.1320 | val_auc=0.97378 val_logloss=0.13238 val_acc=0.9431
Epoch 03: train_loss=0.1246 | val_auc=0.97431 val_logloss=0.13128 val_acc=0.9432
Epoch 04: train_loss=0.1196 | val_auc=0.97407 val_logloss=0.13180 val_acc=0.9431
[Fold 2] AUC=0.97407  LogLoss=0.13180  Acc=0.9431

========== Fold 3/10 ==========
Epoch 01: train_loss=0.1502 | val_auc=0.97164 val_logloss=0.13812 val_acc=0.9397
Epoch 02: train_loss=0.1320 | val_auc=0.97366 val_logloss=0.13246 val_acc=0.9423
Epoch 03: train_loss=0.1249 | val_auc=0.97383 val_logloss=0.13260 val_acc=0.9425
Epoch 04: train_loss=0.1198 | val_auc=0.97376 val_logloss=0.13286 val_acc=0.9430
[Fold 3] AUC=0.97376  LogLoss=0.13286  Acc=0.9430

========== Fold 4/10 ==========
Epoch 01: train_loss=0.1502 | val_auc=0.97109 val_logloss=0.13809 val_acc=0.9401
Epoch 02: train_loss=0.1320 | val_auc=0.97278 val_logloss=0.13331 val_acc=0.9429
Epoch 03: train_loss=0.1251 | val_auc=0.97335 val_logloss=0.13201 val_acc=0.9435
Epoch 04: train_loss=0.1198 | val_auc=0.97339 val_logloss=0.13217 val_acc=0.9442
[Fold 4] AUC=0.97339  LogLoss=0.13217  Acc=0.9442

========== Fold 5/10 ==========
Epoch 01: train_loss=0.1504 | val_auc=0.97208 val_logloss=0.13538 val_acc=0.9421
Epoch 02: train_loss=0.1320 | val_auc=0.97346 val_logloss=0.13203 val_acc=0.9432
Epoch 03: train_loss=0.1247 | val_auc=0.97384 val_logloss=0.13153 val_acc=0.9442
Epoch 04: train_loss=0.1198 | val_auc=0.97379 val_logloss=0.13180 val_acc=0.9441
[Fold 5] AUC=0.97379  LogLoss=0.13180  Acc=0.9441

========== Fold 6/10 ==========
Epoch 01: train_loss=0.1497 | val_auc=0.97207 val_logloss=0.13652 val_acc=0.9406
Epoch 02: train_loss=0.1319 | val_auc=0.97372 val_logloss=0.13197 val_acc=0.9432
Epoch 03: train_loss=0.1250 | val_auc=0.97420 val_logloss=0.13086 val_acc=0.9434
Epoch 04: train_loss=0.1198 | val_auc=0.97409 val_logloss=0.13130 val_acc=0.9431
[Fold 6] AUC=0.97409  LogLoss=0.13130  Acc=0.9431

========== Fold 7/10 ==========
Epoch 01: train_loss=0.1521 | val_auc=0.97360 val_logloss=0.13566 val_acc=0.9407
Epoch 02: train_loss=0.1320 | val_auc=0.97469 val_logloss=0.13065 val_acc=0.9438
Epoch 03: train_loss=0.1250 | val_auc=0.97492 val_logloss=0.12972 val_acc=0.9439
Epoch 04: train_loss=0.1198 | val_auc=0.97478 val_logloss=0.13043 val_acc=0.9433
[Fold 7] AUC=0.97478  LogLoss=0.13043  Acc=0.9433

========== Fold 8/10 ==========
Epoch 01: train_loss=0.1508 | val_auc=0.97186 val_logloss=0.13539 val_acc=0.9423
Epoch 02: train_loss=0.1320 | val_auc=0.97362 val_logloss=0.13131 val_acc=0.9438
Epoch 03: train_loss=0.1248 | val_auc=0.97441 val_logloss=0.12985 val_acc=0.9447
Epoch 04: train_loss=0.1199 | val_auc=0.97435 val_logloss=0.13014 val_acc=0.9448
[Fold 8] AUC=0.97435  LogLoss=0.13014  Acc=0.9448

========== Fold 9/10 ==========
Epoch 01: train_loss=0.1511 | val_auc=0.97205 val_logloss=0.13580 val_acc=0.9407
Epoch 02: train_loss=0.1316 | val_auc=0.97417 val_logloss=0.13120 val_acc=0.9432
Epoch 03: train_loss=0.1249 | val_auc=0.97467 val_logloss=0.12955 val_acc=0.9443
Epoch 04: train_loss=0.1200 | val_auc=0.97448 val_logloss=0.13045 val_acc=0.9435
[Fold 9] AUC=0.97448  LogLoss=0.13045  Acc=0.9435

========== Fold 10/10 ==========
Epoch 01: train_loss=0.1509 | val_auc=0.97376 val_logloss=0.13249 val_acc=0.9430
Epoch 02: train_loss=0.1322 | val_auc=0.97535 val_logloss=0.12722 val_acc=0.9454
Epoch 03: train_loss=0.1249 | val_auc=0.97563 val_logloss=0.12645 val_acc=0.9453
Epoch 04: train_loss=0.1199 | val_auc=0.97537 val_logloss=0.12744 val_acc=0.9450
[Fold 10] AUC=0.97537  LogLoss=0.12744  Acc=0.9450

========== Overall OOF ==========
OOF AUC=0.97421  LogLoss=0.13097  Acc=0.9437
##### REPEAT 2 of 5 #####

========== Fold 1/10 ==========
Epoch 01: train_loss=0.1505 | val_auc=0.97238 val_logloss=0.13821 val_acc=0.9397
Epoch 02: train_loss=0.1317 | val_auc=0.97402 val_logloss=0.13185 val_acc=0.9432
Epoch 03: train_loss=0.1246 | val_auc=0.97418 val_logloss=0.13091 val_acc=0.9439
Epoch 04: train_loss=0.1195 | val_auc=0.97420 val_logloss=0.13116 val_acc=0.9436
[Fold 1] AUC=0.97420  LogLoss=0.13116  Acc=0.9436

========== Fold 2/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97239 val_logloss=0.13579 val_acc=0.9412
Epoch 02: train_loss=0.1321 | val_auc=0.97384 val_logloss=0.13190 val_acc=0.9436
Epoch 03: train_loss=0.1250 | val_auc=0.97403 val_logloss=0.13209 val_acc=0.9434
Epoch 04: train_loss=0.1199 | val_auc=0.97405 val_logloss=0.13184 val_acc=0.9434
[Fold 2] AUC=0.97405  LogLoss=0.13184  Acc=0.9434

========== Fold 3/10 ==========
Epoch 01: train_loss=0.1496 | val_auc=0.97233 val_logloss=0.13631 val_acc=0.9409
Epoch 02: train_loss=0.1315 | val_auc=0.97372 val_logloss=0.13243 val_acc=0.9426
Epoch 03: train_loss=0.1243 | val_auc=0.97398 val_logloss=0.13175 val_acc=0.9427
Epoch 04: train_loss=0.1194 | val_auc=0.97384 val_logloss=0.13243 val_acc=0.9423
[Fold 3] AUC=0.97384  LogLoss=0.13243  Acc=0.9423

========== Fold 4/10 ==========
Epoch 01: train_loss=0.1500 | val_auc=0.97119 val_logloss=0.14093 val_acc=0.9380
Epoch 02: train_loss=0.1318 | val_auc=0.97286 val_logloss=0.13282 val_acc=0.9426
Epoch 03: train_loss=0.1248 | val_auc=0.97338 val_logloss=0.13197 val_acc=0.9431
Epoch 04: train_loss=0.1201 | val_auc=0.97333 val_logloss=0.13209 val_acc=0.9438
[Fold 4] AUC=0.97333  LogLoss=0.13209  Acc=0.9438

========== Fold 5/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97216 val_logloss=0.13594 val_acc=0.9411
Epoch 02: train_loss=0.1319 | val_auc=0.97347 val_logloss=0.13193 val_acc=0.9432
Epoch 03: train_loss=0.1250 | val_auc=0.97393 val_logloss=0.13111 val_acc=0.9439
Epoch 04: train_loss=0.1197 | val_auc=0.97393 val_logloss=0.13138 val_acc=0.9441
[Fold 5] AUC=0.97393  LogLoss=0.13138  Acc=0.9441

========== Fold 6/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97213 val_logloss=0.13584 val_acc=0.9413
Epoch 02: train_loss=0.1322 | val_auc=0.97357 val_logloss=0.13296 val_acc=0.9430
Epoch 03: train_loss=0.1250 | val_auc=0.97411 val_logloss=0.13161 val_acc=0.9437
Epoch 04: train_loss=0.1199 | val_auc=0.97395 val_logloss=0.13176 val_acc=0.9435
[Fold 6] AUC=0.97395  LogLoss=0.13176  Acc=0.9435

========== Fold 7/10 ==========
Epoch 01: train_loss=0.1502 | val_auc=0.97300 val_logloss=0.13617 val_acc=0.9397
Epoch 02: train_loss=0.1323 | val_auc=0.97461 val_logloss=0.13064 val_acc=0.9436
Epoch 03: train_loss=0.1249 | val_auc=0.97483 val_logloss=0.13002 val_acc=0.9437
Epoch 04: train_loss=0.1199 | val_auc=0.97481 val_logloss=0.12993 val_acc=0.9440
[Fold 7] AUC=0.97481  LogLoss=0.12993  Acc=0.9440

========== Fold 8/10 ==========
Epoch 01: train_loss=0.1514 | val_auc=0.97174 val_logloss=0.13554 val_acc=0.9419
Epoch 02: train_loss=0.1326 | val_auc=0.97377 val_logloss=0.13097 val_acc=0.9437
Epoch 03: train_loss=0.1258 | val_auc=0.97426 val_logloss=0.12989 val_acc=0.9450
Epoch 04: train_loss=0.1206 | val_auc=0.97427 val_logloss=0.13056 val_acc=0.9446
[Fold 8] AUC=0.97427  LogLoss=0.13056  Acc=0.9446

========== Fold 9/10 ==========
Epoch 01: train_loss=0.1510 | val_auc=0.97205 val_logloss=0.13578 val_acc=0.9415
Epoch 02: train_loss=0.1321 | val_auc=0.97367 val_logloss=0.13285 val_acc=0.9426
Epoch 03: train_loss=0.1249 | val_auc=0.97408 val_logloss=0.13093 val_acc=0.9433
Epoch 04: train_loss=0.1199 | val_auc=0.97398 val_logloss=0.13157 val_acc=0.9435
[Fold 9] AUC=0.97398  LogLoss=0.13157  Acc=0.9435

========== Fold 10/10 ==========
Epoch 01: train_loss=0.1505 | val_auc=0.97378 val_logloss=0.13112 val_acc=0.9431
Epoch 02: train_loss=0.1321 | val_auc=0.97517 val_logloss=0.12767 val_acc=0.9449
Epoch 03: train_loss=0.1252 | val_auc=0.97552 val_logloss=0.12662 val_acc=0.9454
Epoch 04: train_loss=0.1199 | val_auc=0.97524 val_logloss=0.12739 val_acc=0.9451
[Fold 10] AUC=0.97524  LogLoss=0.12739  Acc=0.9451

========== Overall OOF ==========
OOF AUC=0.97415  LogLoss=0.13101  Acc=0.9438
##### REPEAT 3 of 5 #####

========== Fold 1/10 ==========
Epoch 01: train_loss=0.1518 | val_auc=0.97231 val_logloss=0.13495 val_acc=0.9420
Epoch 02: train_loss=0.1319 | val_auc=0.97399 val_logloss=0.13109 val_acc=0.9433
Epoch 03: train_loss=0.1252 | val_auc=0.97413 val_logloss=0.13108 val_acc=0.9436
Epoch 04: train_loss=0.1201 | val_auc=0.97406 val_logloss=0.13113 val_acc=0.9442
[Fold 1] AUC=0.97406  LogLoss=0.13113  Acc=0.9442

========== Fold 2/10 ==========
Epoch 01: train_loss=0.1501 | val_auc=0.97184 val_logloss=0.14071 val_acc=0.9395
Epoch 02: train_loss=0.1317 | val_auc=0.97359 val_logloss=0.13262 val_acc=0.9433
Epoch 03: train_loss=0.1246 | val_auc=0.97402 val_logloss=0.13178 val_acc=0.9433
Epoch 04: train_loss=0.1195 | val_auc=0.97401 val_logloss=0.13205 val_acc=0.9432
[Fold 2] AUC=0.97401  LogLoss=0.13205  Acc=0.9432

========== Fold 3/10 ==========
Epoch 01: train_loss=0.1506 | val_auc=0.97207 val_logloss=0.13693 val_acc=0.9404
Epoch 02: train_loss=0.1320 | val_auc=0.97374 val_logloss=0.13301 val_acc=0.9420
Epoch 03: train_loss=0.1250 | val_auc=0.97411 val_logloss=0.13212 val_acc=0.9427
Epoch 04: train_loss=0.1200 | val_auc=0.97406 val_logloss=0.13207 val_acc=0.9432
[Fold 3] AUC=0.97406  LogLoss=0.13207  Acc=0.9432

========== Fold 4/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97133 val_logloss=0.13695 val_acc=0.9406
Epoch 02: train_loss=0.1321 | val_auc=0.97253 val_logloss=0.13360 val_acc=0.9420
Epoch 03: train_loss=0.1250 | val_auc=0.97321 val_logloss=0.13262 val_acc=0.9430
Epoch 04: train_loss=0.1198 | val_auc=0.97327 val_logloss=0.13218 val_acc=0.9437
[Fold 4] AUC=0.97327  LogLoss=0.13218  Acc=0.9437

========== Fold 5/10 ==========
Epoch 01: train_loss=0.1508 | val_auc=0.97167 val_logloss=0.13598 val_acc=0.9415
Epoch 02: train_loss=0.1318 | val_auc=0.97361 val_logloss=0.13186 val_acc=0.9431
Epoch 03: train_loss=0.1248 | val_auc=0.97404 val_logloss=0.13135 val_acc=0.9440
Epoch 04: train_loss=0.1199 | val_auc=0.97395 val_logloss=0.13148 val_acc=0.9437
[Fold 5] AUC=0.97395  LogLoss=0.13148  Acc=0.9437

========== Fold 6/10 ==========
Epoch 01: train_loss=0.1497 | val_auc=0.97248 val_logloss=0.13770 val_acc=0.9402
Epoch 02: train_loss=0.1320 | val_auc=0.97351 val_logloss=0.13231 val_acc=0.9425
Epoch 03: train_loss=0.1248 | val_auc=0.97414 val_logloss=0.13108 val_acc=0.9433
Epoch 04: train_loss=0.1199 | val_auc=0.97406 val_logloss=0.13144 val_acc=0.9436
[Fold 6] AUC=0.97406  LogLoss=0.13144  Acc=0.9436

========== Fold 7/10 ==========
Epoch 01: train_loss=0.1495 | val_auc=0.97301 val_logloss=0.13523 val_acc=0.9407
Epoch 02: train_loss=0.1318 | val_auc=0.97458 val_logloss=0.13105 val_acc=0.9428
Epoch 03: train_loss=0.1249 | val_auc=0.97481 val_logloss=0.12996 val_acc=0.9437
Epoch 04: train_loss=0.1200 | val_auc=0.97475 val_logloss=0.13037 val_acc=0.9437
[Fold 7] AUC=0.97475  LogLoss=0.13037  Acc=0.9437

========== Fold 8/10 ==========
Epoch 01: train_loss=0.1522 | val_auc=0.97230 val_logloss=0.13572 val_acc=0.9421
Epoch 02: train_loss=0.1323 | val_auc=0.97355 val_logloss=0.13208 val_acc=0.9443
Epoch 03: train_loss=0.1251 | val_auc=0.97434 val_logloss=0.12968 val_acc=0.9448
Epoch 04: train_loss=0.1203 | val_auc=0.97429 val_logloss=0.13032 val_acc=0.9450
[Fold 8] AUC=0.97429  LogLoss=0.13032  Acc=0.9450

========== Fold 9/10 ==========
Epoch 01: train_loss=0.1496 | val_auc=0.97228 val_logloss=0.13526 val_acc=0.9412
Epoch 02: train_loss=0.1322 | val_auc=0.97392 val_logloss=0.13121 val_acc=0.9435
Epoch 03: train_loss=0.1251 | val_auc=0.97435 val_logloss=0.13055 val_acc=0.9438
Epoch 04: train_loss=0.1199 | val_auc=0.97432 val_logloss=0.13048 val_acc=0.9438
[Fold 9] AUC=0.97432  LogLoss=0.13048  Acc=0.9438

========== Fold 10/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97354 val_logloss=0.13295 val_acc=0.9423
Epoch 02: train_loss=0.1326 | val_auc=0.97511 val_logloss=0.12810 val_acc=0.9450
Epoch 03: train_loss=0.1255 | val_auc=0.97548 val_logloss=0.12714 val_acc=0.9449
Epoch 04: train_loss=0.1204 | val_auc=0.97531 val_logloss=0.12742 val_acc=0.9450
[Fold 10] AUC=0.97531  LogLoss=0.12742  Acc=0.9450

========== Overall OOF ==========
OOF AUC=0.97420  LogLoss=0.13090  Acc=0.9439
##### REPEAT 4 of 5 #####

========== Fold 1/10 ==========
Epoch 01: train_loss=0.1500 | val_auc=0.97209 val_logloss=0.13576 val_acc=0.9421
Epoch 02: train_loss=0.1323 | val_auc=0.97366 val_logloss=0.13219 val_acc=0.9428
Epoch 03: train_loss=0.1251 | val_auc=0.97418 val_logloss=0.13079 val_acc=0.9441
Epoch 04: train_loss=0.1200 | val_auc=0.97407 val_logloss=0.13126 val_acc=0.9442
[Fold 1] AUC=0.97407  LogLoss=0.13126  Acc=0.9442

========== Fold 2/10 ==========
Epoch 01: train_loss=0.1509 | val_auc=0.97259 val_logloss=0.13511 val_acc=0.9416
Epoch 02: train_loss=0.1318 | val_auc=0.97383 val_logloss=0.13197 val_acc=0.9424
Epoch 03: train_loss=0.1246 | val_auc=0.97437 val_logloss=0.13137 val_acc=0.9432
Epoch 04: train_loss=0.1197 | val_auc=0.97436 val_logloss=0.13142 val_acc=0.9438
[Fold 2] AUC=0.97436  LogLoss=0.13142  Acc=0.9438

========== Fold 3/10 ==========
Epoch 01: train_loss=0.1501 | val_auc=0.97188 val_logloss=0.13773 val_acc=0.9404
Epoch 02: train_loss=0.1317 | val_auc=0.97339 val_logloss=0.13361 val_acc=0.9424
Epoch 03: train_loss=0.1249 | val_auc=0.97389 val_logloss=0.13236 val_acc=0.9428
Epoch 04: train_loss=0.1197 | val_auc=0.97393 val_logloss=0.13236 val_acc=0.9428
[Fold 3] AUC=0.97393  LogLoss=0.13236  Acc=0.9428

========== Fold 4/10 ==========
Epoch 01: train_loss=0.1493 | val_auc=0.97090 val_logloss=0.13747 val_acc=0.9411
Epoch 02: train_loss=0.1316 | val_auc=0.97311 val_logloss=0.13228 val_acc=0.9432
Epoch 03: train_loss=0.1247 | val_auc=0.97339 val_logloss=0.13165 val_acc=0.9438
Epoch 04: train_loss=0.1199 | val_auc=0.97348 val_logloss=0.13176 val_acc=0.9443
[Fold 4] AUC=0.97348  LogLoss=0.13176  Acc=0.9443

========== Fold 5/10 ==========
Epoch 01: train_loss=0.1505 | val_auc=0.97210 val_logloss=0.13572 val_acc=0.9415
Epoch 02: train_loss=0.1319 | val_auc=0.97345 val_logloss=0.13252 val_acc=0.9428
Epoch 03: train_loss=0.1247 | val_auc=0.97380 val_logloss=0.13159 val_acc=0.9438
Epoch 04: train_loss=0.1198 | val_auc=0.97379 val_logloss=0.13193 val_acc=0.9441
[Fold 5] AUC=0.97379  LogLoss=0.13193  Acc=0.9441

========== Fold 6/10 ==========
Epoch 01: train_loss=0.1500 | val_auc=0.97262 val_logloss=0.13485 val_acc=0.9421
Epoch 02: train_loss=0.1315 | val_auc=0.97381 val_logloss=0.13179 val_acc=0.9438
Epoch 03: train_loss=0.1247 | val_auc=0.97420 val_logloss=0.13158 val_acc=0.9430
Epoch 04: train_loss=0.1195 | val_auc=0.97411 val_logloss=0.13151 val_acc=0.9438
[Fold 6] AUC=0.97411  LogLoss=0.13151  Acc=0.9438

========== Fold 7/10 ==========
Epoch 01: train_loss=0.1509 | val_auc=0.97304 val_logloss=0.13465 val_acc=0.9417
Epoch 02: train_loss=0.1320 | val_auc=0.97425 val_logloss=0.13159 val_acc=0.9431
Epoch 03: train_loss=0.1248 | val_auc=0.97505 val_logloss=0.12963 val_acc=0.9435
Epoch 04: train_loss=0.1198 | val_auc=0.97492 val_logloss=0.13005 val_acc=0.9442
[Fold 7] AUC=0.97492  LogLoss=0.13005  Acc=0.9442

========== Fold 8/10 ==========
Epoch 01: train_loss=0.1514 | val_auc=0.97211 val_logloss=0.13444 val_acc=0.9428
Epoch 02: train_loss=0.1319 | val_auc=0.97360 val_logloss=0.13127 val_acc=0.9437
Epoch 03: train_loss=0.1248 | val_auc=0.97422 val_logloss=0.12987 val_acc=0.9450
Epoch 04: train_loss=0.1197 | val_auc=0.97419 val_logloss=0.13060 val_acc=0.9450
[Fold 8] AUC=0.97419  LogLoss=0.13060  Acc=0.9450

========== Fold 9/10 ==========
Epoch 01: train_loss=0.1509 | val_auc=0.97287 val_logloss=0.13435 val_acc=0.9415
Epoch 02: train_loss=0.1322 | val_auc=0.97431 val_logloss=0.13112 val_acc=0.9435
Epoch 03: train_loss=0.1252 | val_auc=0.97441 val_logloss=0.13013 val_acc=0.9435
Epoch 04: train_loss=0.1200 | val_auc=0.97439 val_logloss=0.13044 val_acc=0.9439
[Fold 9] AUC=0.97439  LogLoss=0.13044  Acc=0.9439

========== Fold 10/10 ==========
Epoch 01: train_loss=0.1517 | val_auc=0.97362 val_logloss=0.13206 val_acc=0.9429
Epoch 02: train_loss=0.1327 | val_auc=0.97500 val_logloss=0.12876 val_acc=0.9443
Epoch 03: train_loss=0.1253 | val_auc=0.97537 val_logloss=0.12698 val_acc=0.9452
Epoch 04: train_loss=0.1201 | val_auc=0.97513 val_logloss=0.12779 val_acc=0.9453
[Fold 10] AUC=0.97513  LogLoss=0.12779  Acc=0.9453

========== Overall OOF ==========
OOF AUC=0.97421  LogLoss=0.13091  Acc=0.9441
##### REPEAT 5 of 5 #####

========== Fold 1/10 ==========
Epoch 01: train_loss=0.1506 | val_auc=0.97193 val_logloss=0.13638 val_acc=0.9413
Epoch 02: train_loss=0.1323 | val_auc=0.97390 val_logloss=0.13126 val_acc=0.9433
Epoch 03: train_loss=0.1251 | val_auc=0.97427 val_logloss=0.13060 val_acc=0.9440
Epoch 04: train_loss=0.1200 | val_auc=0.97419 val_logloss=0.13125 val_acc=0.9444
[Fold 1] AUC=0.97419  LogLoss=0.13125  Acc=0.9444

========== Fold 2/10 ==========
Epoch 01: train_loss=0.1507 | val_auc=0.97233 val_logloss=0.13649 val_acc=0.9413
Epoch 02: train_loss=0.1321 | val_auc=0.97398 val_logloss=0.13157 val_acc=0.9433
Epoch 03: train_loss=0.1252 | val_auc=0.97427 val_logloss=0.13097 val_acc=0.9437
Epoch 04: train_loss=0.1202 | val_auc=0.97422 val_logloss=0.13132 val_acc=0.9433
[Fold 2] AUC=0.97422  LogLoss=0.13132  Acc=0.9433

========== Fold 3/10 ==========
Epoch 01: train_loss=0.1499 | val_auc=0.97183 val_logloss=0.13697 val_acc=0.9401
Epoch 02: train_loss=0.1320 | val_auc=0.97366 val_logloss=0.13300 val_acc=0.9416
Epoch 03: train_loss=0.1248 | val_auc=0.97424 val_logloss=0.13165 val_acc=0.9432
Epoch 04: train_loss=0.1196 | val_auc=0.97403 val_logloss=0.13214 val_acc=0.9431
[Fold 3] AUC=0.97403  LogLoss=0.13214  Acc=0.9431

========== Fold 4/10 ==========
Epoch 01: train_loss=0.1491 | val_auc=0.97051 val_logloss=0.13880 val_acc=0.9393
Epoch 02: train_loss=0.1317 | val_auc=0.97312 val_logloss=0.13253 val_acc=0.9431
Epoch 03: train_loss=0.1247 | val_auc=0.97347 val_logloss=0.13161 val_acc=0.9436
Epoch 04: train_loss=0.1198 | val_auc=0.97355 val_logloss=0.13174 val_acc=0.9437
[Fold 4] AUC=0.97355  LogLoss=0.13174  Acc=0.9437

========== Fold 5/10 ==========
Epoch 01: train_loss=0.1508 | val_auc=0.97196 val_logloss=0.13565 val_acc=0.9421
Epoch 02: train_loss=0.1318 | val_auc=0.97353 val_logloss=0.13232 val_acc=0.9431
Epoch 03: train_loss=0.1246 | val_auc=0.97400 val_logloss=0.13071 val_acc=0.9443
Epoch 04: train_loss=0.1194 | val_auc=0.97386 val_logloss=0.13148 val_acc=0.9442
[Fold 5] AUC=0.97386  LogLoss=0.13148  Acc=0.9442

========== Fold 6/10 ==========
Epoch 01: train_loss=0.1503 | val_auc=0.97222 val_logloss=0.13572 val_acc=0.9414
Epoch 02: train_loss=0.1313 | val_auc=0.97398 val_logloss=0.13147 val_acc=0.9427
Epoch 03: train_loss=0.1245 | val_auc=0.97422 val_logloss=0.13067 val_acc=0.9432
Epoch 04: train_loss=0.1196 | val_auc=0.97414 val_logloss=0.13117 val_acc=0.9430
[Fold 6] AUC=0.97414  LogLoss=0.13117  Acc=0.9430

========== Fold 7/10 ==========
Epoch 01: train_loss=0.1505 | val_auc=0.97347 val_logloss=0.13362 val_acc=0.9414
Epoch 02: train_loss=0.1318 | val_auc=0.97467 val_logloss=0.13037 val_acc=0.9433
Epoch 03: train_loss=0.1248 | val_auc=0.97483 val_logloss=0.12996 val_acc=0.9439
Epoch 04: train_loss=0.1195 | val_auc=0.97460 val_logloss=0.13082 val_acc=0.9436

In [18]:
m = roc_auc_score(train.y.to_numpy(), oof)
print(f"NN (Train More) CV = {m}")

NN (Train More) CV = 0.9750620309284384

# Create NN (Train More) Submission CSV

In [19]:
sub = pd.read_csv(f"{PATH}sample_submission.csv")
sub['y'] = preds
sub.to_csv("submission_nn_train_more.csv",index=False)
np.save("oof_nn_train_more",oof)
print('Submission shape',sub.shape)
#sub.head()

Submission shape (250000, 2)

# Create XGB (Train More) Submission CSV

In [20]:
sub = pd.read_csv(f"{PATH}sample_submission.csv")
preds_xgb = (test_preds+test_preds2)/2. 
sub['y'] = preds_xgb
sub.to_csv("submission_xgb_train_more.csv",index=False)
np.save("oof_xgb_rows_train_more",oof_preds)
np.save("oof_xgb_cols_train_more",oof_preds2)
print('Submission shape',sub.shape)
#sub.head()

Submission shape (250000, 2)

# Ensemble - XGB and NN (Train More) - CV Score

In [21]:
oof_xgb = (oof_preds+oof_preds2)/2.
m = roc_auc_score(train.y.to_numpy(), oof_xgb)
print(f"Both XGB rows and XGB cols (Train More) CV = {m}")

Both XGB rows and XGB cols (Train More) CV = 0.9764041800768835

In [22]:
best_m = 0
best_w = 0
for w in np.arange(0,1.01,0.01):
    oof_ensemble = (1-w)*oof_xgb + w*oof
    m = roc_auc_score(train.y.to_numpy(), oof_ensemble)
    if m>best_m:
        best_m = m
        best_w = w
        
oof_ensemble = (1-best_w)*oof_xgb + best_w*oof
m = roc_auc_score(train.y.to_numpy(), oof_ensemble)
print(f"Ensemble XGB and NN (Train More) CV = {m}")
print(f" using best NN weight = {best_w}")

Ensemble XGB and NN (Train More) CV = 0.97661573267636
 using best NN weight = 0.27

# Create - XGB and NN (Train More) - Submission CSV

In [23]:
xgb_preds = preds_xgb 
sub = pd.read_csv(f"{PATH}sample_submission.csv")
sub['y'] = (1-best_w)*xgb_preds + best_w*preds
sub.to_csv("submission_ensemble_train_more.csv",index=False)
print('Submission shape',sub.shape)
sub.head()

Submission shape (250000, 2)

       id         y
0  750000  0.000796
1  750001  0.070609
2  750002  0.000149
3  750003  0.000057
4  750004  0.006373